spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/microservice_bank_request
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: qwerty
    platform: POSTGRESQL
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
  output:
    ansi:
      enabled: always
  application:
    name: bank-request
server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/